### PR TITLE
add capability to email a pdf of a webpage. Requires wkhtmltopdf

### PR DESCRIPTION
**Pull request by TangoYankee**
__Friendly Reminder Checklist:__
- [ ] Code follows guidelines [follows guidelines](https://github.com/openoakland/TrashTalk/blob/master/CONTRIBUTE.md#codeguidelines
- [ ] Tests have passed locally.
- [ ] Linter score is 7.5 or above.
- [ ] References to relevant issues added in the description.
- [ ] Updates to migrations, tests and requirements are included as necessary.

@protosac
@thinhngo 

__Description:__
Send PDF to Public Works [Issue 153](https://github.com/openoakland/trashtalk/issues/153)
1. [wkhtmltopdf](https://wktohtmlpdf.org) takes a screen grab of a cleanup
2. screen grab is saved as a pdf in static/pdf folder
3. pdf is emailed
4. pdf is deleted from static/pdf

Future work: 
1. Build proper tool request form. 
2. Rewrite url to direct to proper tool request form. 
3. Reformat URL so it is no longer hard-coded as local address.
4. Find a place to host wkhtmltopdf and then re-write the reference to its file path
5. Not sure how to include wkhtmltopdf in requirements. It is an .exe, not .py

### CODE REVIEW

**Comment by TangoYankee** [comment]
Forgot to add slugify to requirements

**Comment by TangoYankee** [comment]
@Protosac 
@thinhngo 
Finally dove into pylint. Utils needs to bring its score up. I'll make a few changes and resubmit this pull request. I'll also add slugify to requirements.

**Comment by thinhngo** [comment]
This request still feels very odd to me. Having worked with HTML to PDF generators before, I know they can be temperamental. I'm still not sure why a PDF would serve them better than a CSV file, which would be easier for us to generate and I'd imagine a CSV would be easier for them to parse. Can we revisit next time we meet in person?

**Review by mosdevly — CHANGES_REQUESTED** [review]
Yay for PDF creation! I only question why we're sending a PDF on password reset. Let me know if i"m misunderstanding what's in the PDF.

Otherwise I think we can use the PDF tool implementation, but may  not need to send a PDF for a password reset.

**Comment by TangoYankee** [comment]
@Protosac This pull request is awkward. Ultimately, the PDF will grab the tool request form. However, Thinh was building that page. Consequently, it temporarily grabs cleanup-detail. Once the tool request summary is finished, the page reference can be changed to that. Also, I'm not sure where the idea of a PDF for password reset is coming from. It's a PDF summary of a Cleanup to Coordinate with Public Works. 

@thinhngo The PDF functionality is temporary. It is awkward and sub-optimal. However, it allows us to integrate with the Public Works process while Public Works remains independent from TrashTalk. In short time, we can replace the PDFs with something more elegant. However, we must first meet them where they are.

**Pull request closed without merging**
